### PR TITLE
fix account update flashes

### LINKED ISSUE #341: Changing email address
When changing my email address (and my current password) I get the error: `translation missing: en.user_updated`, and my email address remains unchanged:

screen shot 2015-07-20 at 16 54 30

### PR DESCRIPTION
**Pull request by jurre**
This should fix #341, makes it more clear what's happening :)

### CODE REVIEW

File: app/controllers/users_controller.rb [hunk 1]
```diff
@@ -15,8 +15,11 @@ def edit
 
   def update
     @user = current_user
+     prev_unconfirmed_email = @user.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
```
Comment (jurre) [inline app/controllers/users_controller.rb]: Your face is too long
